# Name of your application. Used to uniquely configure containers.
service: cos

# Your container image on GHCR
image: ghcr.io/superficialadam/chief-of-staff-v2

# Deploy to these servers.
servers:
  - 65.21.198.81

# SSH settings
ssh:
  user: adam

# Kamal proxy handles TLS + routing on the same box
proxy:
  host: cos.dev.its75am.com
  healthcheck:
    path: /up
    interval: 5
    timeout: 2

# Credentials for your image host (read-only on the server)
registry:
  server: ghcr.io
  username: <%= ENV["GHCR_USER"] %>
  password: <%= ENV["GHCR_TOKEN"] %>

# ENV for the container
env:
  clear:
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: "1"
    RAILS_SERVE_STATIC_FILES: "1"
    PORT: "80"                 # Dockerfile exposes 80; Rails starts via thrust
    SOLID_QUEUE_IN_PUMA: "true" # simple single-box setup for now
  secret:
    - RAILS_MASTER_KEY
    - OPENAI_PASSWORD
    - OPENAI_API_KEY
    - PGHOST
    - PGPORT
    - PGDATABASE
    - PGUSER
    - PGPASSWORD
    - TELEGRAM_BOT_TOKEN
    - TELEGRAM_CHAT_ID

# Persist Active Storage uploads (host path you can back up)
volumes:
  - "/var/lib/cos/storage:/rails/storage"

# Bridge fingerprinted assets between versions to avoid 404s on deploy
asset_path: /rails/public/assets

# Builder options
builder:
  arch: amd64

# Handy aliases
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
